# -*- coding: utf-8 -*-
"""Linear_Regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QBxwFNri1ifPYuGxoi7bdi9Ypp4d4sF5
"""

import tensorflow as tf
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/keras tutorial/tutorial 1/IowaHousingPrices.csv')

SquareFeet = df[['SquareFeet']].values
SalePrice = df[['SalePrice']].values

model = tf.keras.Sequential()
model.add(tf.keras.layers.Dense(1, input_shape=(1,)))
model.compile(tf.keras.optimizers.Adam(learning_rate=1), 'mean_squared_error')

model.fit(SquareFeet, SalePrice, epochs=30, batch_size=10)

df.plot(kind='scatter', x='SquareFeet', y='SalePrice', title='House Prices Prediction')
y_pred = model.predict(SquareFeet)
plt.plot(SquareFeet, y_pred, color = 'red')

newSF = 2000
print(model.predict([newSF]))

